apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80          # External port for access
      targetPort: 4499  # Container port inside pods
  type: NodePort       # Use LoadBalancer for cloud clusters

